// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eKarton.Databases;

namespace eKarton.Migrations
{
    [DbContext(typeof(ekartonRContext))]
    [Migration("20220902091401_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Latin1_General_CI_AI")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eKarton.Databases.Administrator", b =>
                {
                    b.Property<int>("AdministratorId")
                        .HasColumnType("int");

                    b.Property<int>("BolnicaId")
                        .HasColumnType("int");

                    b.Property<string>("DatumRodjenja")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Prebivaliste")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AdministratorId");

                    b.HasIndex("BolnicaId");

                    b.ToTable("Administrator");

                    b.HasData(
                        new
                        {
                            AdministratorId = 1007,
                            BolnicaId = 1000,
                            DatumRodjenja = "1998/12/16",
                            Email = "arijanahusic@gmail.com",
                            Ime = "Arijana",
                            Prebivaliste = "Sarajevo",
                            Prezime = "Husic",
                            Telefon = "063 246 022"
                        });
                });

            modelBuilder.Entity("eKarton.Databases.Bolnica", b =>
                {
                    b.Property<int>("BolnicaId")
                        .HasColumnType("int");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("BolnicaId");

                    b.ToTable("Bolnica");

                    b.HasData(
                        new
                        {
                            BolnicaId = 1000,
                            Adresa = " Maršala Tita 294, Mostar 88000",
                            Email = "bolnica@gmail.com",
                            Naziv = "Kantonalna bolnica 'Dr.Safet Mujić'",
                            Telefon = " 036 503-100"
                        });
                });

            modelBuilder.Entity("eKarton.Databases.DodjeljeniDoktor", b =>
                {
                    b.Property<int>("PacijentId")
                        .HasColumnType("int");

                    b.Property<int>("DoktorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DatumOd")
                        .HasColumnType("date");

                    b.HasKey("PacijentId", "DoktorId");

                    b.HasIndex("DoktorId");

                    b.ToTable("DodjeljeniDoktor");

                    b.HasData(
                        new
                        {
                            PacijentId = 5001,
                            DoktorId = 3001,
                            DatumOd = new DateTime(2022, 9, 2, 11, 13, 54, 178, DateTimeKind.Local).AddTicks(2469)
                        },
                        new
                        {
                            PacijentId = 5002,
                            DoktorId = 3007,
                            DatumOd = new DateTime(2022, 9, 2, 11, 13, 54, 178, DateTimeKind.Local).AddTicks(3889)
                        },
                        new
                        {
                            PacijentId = 5003,
                            DoktorId = 3008,
                            DatumOd = new DateTime(2022, 9, 2, 11, 13, 54, 178, DateTimeKind.Local).AddTicks(3970)
                        });
                });

            modelBuilder.Entity("eKarton.Databases.Doktor", b =>
                {
                    b.Property<int>("DoktorId")
                        .HasColumnType("int");

                    b.Property<string>("DatumRodjenja")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Jmbg")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("JMBG");

                    b.Property<int>("OdjelId")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Spol")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DoktorId");

                    b.HasIndex("OdjelId");

                    b.ToTable("Doktor");

                    b.HasData(
                        new
                        {
                            DoktorId = 3001,
                            DatumRodjenja = "1998/12/15",
                            Email = "stanija@gmail.com",
                            Grad = "Sarajevo",
                            Ime = "STANIJA",
                            Jmbg = "1215988789654",
                            OdjelId = 2001,
                            Prezime = "TOKMAKČIJA",
                            Spol = "Z",
                            Telefon = "063 246 022"
                        },
                        new
                        {
                            DoktorId = 3002,
                            DatumRodjenja = "1988-01-02",
                            Email = "radas@gmail.com",
                            Grad = "Mostar",
                            Ime = "Rada",
                            Jmbg = "0102988789654",
                            OdjelId = 2006,
                            Prezime = "Šandrk",
                            Spol = "Z",
                            Telefon = "063 246 722"
                        },
                        new
                        {
                            DoktorId = 3003,
                            DatumRodjenja = "1980-10-02",
                            Email = "jelenap@gmail.com",
                            Grad = "Sarajevo",
                            Ime = "Jelena",
                            Jmbg = "1002980789654",
                            OdjelId = 2006,
                            Prezime = "Pavlovic",
                            Spol = "Z",
                            Telefon = "063 216 722"
                        },
                        new
                        {
                            DoktorId = 3004,
                            DatumRodjenja = "1975-12-09",
                            Email = "markom@gmail.com",
                            Grad = "Sarajevo",
                            Ime = "Marko",
                            Jmbg = "2099750789654",
                            OdjelId = 2005,
                            Prezime = "Martinac",
                            Spol = "M",
                            Telefon = "063 216 722"
                        },
                        new
                        {
                            DoktorId = 3005,
                            DatumRodjenja = "1990 - 07 - 05",
                            Email = "bznada@gmail.com",
                            Grad = "Mostar",
                            Ime = "Nada",
                            Jmbg = "0507990078965",
                            OdjelId = 2005,
                            Prezime = "Bazina",
                            Spol = "Z",
                            Telefon = "062 216 722"
                        },
                        new
                        {
                            DoktorId = 3006,
                            DatumRodjenja = "1989 - 06 - 28",
                            Email = "adnaz@gmail.com",
                            Grad = "Mostar",
                            Ime = "Adna",
                            Jmbg = "2806989789654",
                            OdjelId = 2004,
                            Prezime = "Zalihic",
                            Spol = "Z",
                            Telefon = "061 216 722"
                        },
                        new
                        {
                            DoktorId = 3007,
                            DatumRodjenja = "1980 - 02 - 03",
                            Email = "rankog@gmail.com",
                            Grad = "Tuzla",
                            Ime = "Ranko",
                            Jmbg = "2039801236547",
                            OdjelId = 2001,
                            Prezime = "Gacic",
                            Spol = "M",
                            Telefon = "062 317 722"
                        },
                        new
                        {
                            DoktorId = 3008,
                            DatumRodjenja = "1970 - 11 - 11",
                            Email = "nikolinas@gmail.com",
                            Grad = "Mostar",
                            Ime = "Nikolina",
                            Jmbg = "1111197523974",
                            OdjelId = 2001,
                            Prezime = "Soce",
                            Spol = "Z",
                            Telefon = "062 216 722"
                        },
                        new
                        {
                            DoktorId = 3009,
                            DatumRodjenja = "1971 - 03 - 22",
                            Email = "editas@gmail.com",
                            Grad = "Stolac",
                            Ime = "Edita",
                            Jmbg = "2203197154239",
                            OdjelId = 2001,
                            Prezime = "Sopta",
                            Spol = "Z",
                            Telefon = "062 216 722"
                        },
                        new
                        {
                            DoktorId = 3010,
                            DatumRodjenja = "1971 - 05 - 11",
                            Email = "gordanap@gmail.com",
                            Grad = "Mostar",
                            Ime = "Gordana",
                            Jmbg = "1105971289654",
                            OdjelId = 2001,
                            Prezime = "Pivic",
                            Spol = "Z",
                            Telefon = "062 216 722"
                        },
                        new
                        {
                            DoktorId = 3011,
                            DatumRodjenja = "1980 - 11 - 19",
                            Email = "senadv@gmail.com",
                            Grad = "Mostar",
                            Ime = "Senad",
                            Jmbg = "1911980647123",
                            OdjelId = 2002,
                            Prezime = "Vujica",
                            Spol = "M",
                            Telefon = "062 216 722"
                        },
                        new
                        {
                            DoktorId = 3012,
                            DatumRodjenja = "1985 - 06 - 22",
                            Email = "sandrab@gmail.com",
                            Grad = "Sarajevo",
                            Ime = "Sandra",
                            Jmbg = "2206985452136",
                            OdjelId = 2003,
                            Prezime = "Brajkovic",
                            Spol = "Z",
                            Telefon = "062 216 722"
                        });
                });

            modelBuilder.Entity("eKarton.Databases.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LozinkaSalt")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("KorisnikId");

                    b.ToTable("Korisnik");

                    b.HasData(
                        new
                        {
                            KorisnikId = 1001,
                            Ime = "Arijana",
                            KorisnickoIme = "admin",
                            LozinkaHash = "1Ikzb+4T3m/mSsSAR/nHhHf76fg=",
                            LozinkaSalt = "IPO1Gbirb4VplijalXCMJA==",
                            Prezime = "Husic"
                        },
                        new
                        {
                            KorisnikId = 1002,
                            Ime = "Medisa",
                            KorisnickoIme = "korisnik",
                            LozinkaHash = "tYVhM9e1TpmlQVGMlm9/Q3tkeEQ=",
                            LozinkaSalt = "RH0O7zwBCMV4DgpZNcdDQQ==",
                            Prezime = "Satara"
                        });
                });

            modelBuilder.Entity("eKarton.Databases.KorisnikUloga", b =>
                {
                    b.Property<int>("KorisnikUlogeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DatumIzmjenje")
                        .HasColumnType("date");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("UlogaId")
                        .HasColumnType("int");

                    b.HasKey("KorisnikUlogeId")
                        .HasName("PK_KorisnikUloge");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("UlogaId");

                    b.ToTable("KorisnikUloga");

                    b.HasData(
                        new
                        {
                            KorisnikUlogeId = 1,
                            DatumIzmjenje = new DateTime(2022, 9, 2, 11, 13, 54, 149, DateTimeKind.Local).AddTicks(8895),
                            KorisnikId = 1001,
                            UlogaId = 1
                        },
                        new
                        {
                            KorisnikUlogeId = 2,
                            DatumIzmjenje = new DateTime(2022, 9, 2, 11, 13, 54, 163, DateTimeKind.Local).AddTicks(2023),
                            KorisnikId = 1002,
                            UlogaId = 2
                        });
                });

            modelBuilder.Entity("eKarton.Databases.Nalaz", b =>
                {
                    b.Property<int>("NalazId")
                        .HasColumnType("int");

                    b.Property<string>("Datum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LicnaAnamneza")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PacijentId")
                        .HasColumnType("int");

                    b.Property<string>("PorodicnaAnamneza")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RadnaAnamneza")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("NalazId");

                    b.HasIndex("PacijentId");

                    b.ToTable("Nalaz");

                    b.HasData(
                        new
                        {
                            NalazId = 8001,
                            Datum = "2021-12-22",
                            LicnaAnamneza = "Upala uha",
                            PacijentId = 5001,
                            PorodicnaAnamneza = "Nema",
                            RadnaAnamneza = "Nema"
                        },
                        new
                        {
                            NalazId = 8002,
                            Datum = "2021-04-05",
                            LicnaAnamneza = "Ukljesten vrat",
                            PacijentId = 5001,
                            PorodicnaAnamneza = "Nema",
                            RadnaAnamneza = "Nema"
                        },
                        new
                        {
                            NalazId = 8003,
                            Datum = "2022-03-22",
                            LicnaAnamneza = "Upala pluca",
                            PacijentId = 5002,
                            PorodicnaAnamneza = "Secer",
                            RadnaAnamneza = "Nema"
                        },
                        new
                        {
                            NalazId = 8004,
                            Datum = "2022-09-01",
                            LicnaAnamneza = "Rutinska kontrola",
                            PacijentId = 5003,
                            PorodicnaAnamneza = "Nema",
                            RadnaAnamneza = "Nema"
                        });
                });

            modelBuilder.Entity("eKarton.Databases.Oboljenje", b =>
                {
                    b.Property<int>("OboljenjeId")
                        .HasColumnType("int");

                    b.Property<string>("Dijagnoza")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Terapija")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("OboljenjeId");

                    b.ToTable("Oboljenje");

                    b.HasData(
                        new
                        {
                            OboljenjeId = 8010,
                            Dijagnoza = "Dijabetis",
                            Terapija = "Inzulin"
                        },
                        new
                        {
                            OboljenjeId = 8020,
                            Dijagnoza = "Astma",
                            Terapija = "Pumpica"
                        });
                });

            modelBuilder.Entity("eKarton.Databases.OcjenaDoktora", b =>
                {
                    b.Property<int>("OcjenaId")
                        .HasColumnType("int");

                    b.Property<bool?>("Anonimno")
                        .HasColumnType("bit");

                    b.Property<int>("DoktorId")
                        .HasColumnType("int");

                    b.Property<int>("Ocjena")
                        .HasColumnType("int");

                    b.Property<string>("Razlog")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OcjenaId")
                        .HasName("PK_Ocjena");

                    b.HasIndex("DoktorId");

                    b.ToTable("OcjenaDoktora");

                    b.HasData(
                        new
                        {
                            OcjenaId = 3100,
                            Anonimno = true,
                            DoktorId = 3001,
                            Ocjena = 4,
                            Razlog = "Vrlo dobar"
                        },
                        new
                        {
                            OcjenaId = 3200,
                            Anonimno = true,
                            DoktorId = 3002,
                            Ocjena = 5,
                            Razlog = "Odlican"
                        },
                        new
                        {
                            OcjenaId = 3300,
                            Anonimno = true,
                            DoktorId = 3009,
                            Ocjena = 4,
                            Razlog = "Vrlo dobar"
                        });
                });

            modelBuilder.Entity("eKarton.Databases.Odjel", b =>
                {
                    b.Property<int>("OdjelId")
                        .HasColumnType("int");

                    b.Property<int>("BolnicaId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("OdjelId");

                    b.HasIndex("BolnicaId");

                    b.ToTable("Odjel");

                    b.HasData(
                        new
                        {
                            OdjelId = 2001,
                            BolnicaId = 1000,
                            Naziv = "Obiteljska medicina",
                            Telefon = "033/853-222"
                        },
                        new
                        {
                            OdjelId = 2002,
                            BolnicaId = 1000,
                            Naziv = "Stomatologija",
                            Telefon = "033/853-555"
                        },
                        new
                        {
                            OdjelId = 2003,
                            BolnicaId = 1000,
                            Naziv = "Neurologija",
                            Telefon = "033/853-552"
                        },
                        new
                        {
                            OdjelId = 2004,
                            BolnicaId = 1000,
                            Naziv = "Ginekologija",
                            Telefon = "033/853-553"
                        },
                        new
                        {
                            OdjelId = 2005,
                            BolnicaId = 1000,
                            Naziv = "Psihijatrija",
                            Telefon = "033/853-543"
                        },
                        new
                        {
                            OdjelId = 2006,
                            BolnicaId = 1000,
                            Naziv = "Pedijatrija",
                            Telefon = "033/853-743"
                        });
                });

            modelBuilder.Entity("eKarton.Databases.Osiguranje", b =>
                {
                    b.Property<int>("OsiguranjeId")
                        .HasColumnType("int");

                    b.Property<string>("Osiguranik")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OsiguranjeId");

                    b.ToTable("Osiguranje");

                    b.HasData(
                        new
                        {
                            OsiguranjeId = 4001,
                            Osiguranik = "Intera"
                        },
                        new
                        {
                            OsiguranjeId = 4002,
                            Osiguranik = "Josip 'Biro'"
                        },
                        new
                        {
                            OsiguranjeId = 4003,
                            Osiguranik = "Hercegovina promet"
                        });
                });

            modelBuilder.Entity("eKarton.Databases.Pacijent", b =>
                {
                    b.Property<int>("PacijentId")
                        .HasColumnType("int");

                    b.Property<string>("Alergican")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BrojKartona")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DatumRodjenja")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HronicneBolesti")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Jmbg")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("JMBG");

                    b.Property<bool?>("Koagulopatije")
                        .HasColumnType("bit");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("KrvnaGrupa")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LozinkaSalt")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MjestoRodjenja")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Prebivaliste")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RhFaktor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Spol")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PacijentId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Pacijent");

                    b.HasData(
                        new
                        {
                            PacijentId = 5001,
                            Alergican = "Ne",
                            BrojKartona = "14B579",
                            DatumRodjenja = "1998-12-11",
                            HronicneBolesti = "Nema",
                            Ime = "Josip",
                            Jmbg = "1211998796541",
                            Koagulopatije = false,
                            KorisnickoIme = "pacijent1",
                            KorisnikId = 1002,
                            KrvnaGrupa = "AB",
                            LozinkaHash = "0xBZaX/f1WGPo+l/3IkzB55lLGY=",
                            LozinkaSalt = "9DtOOxfKEOqzx/vHnjsGLQ==",
                            MjestoRodjenja = "Mostar",
                            Prebivaliste = "Mostar",
                            Prezime = "Bojcic",
                            RhFaktor = "+",
                            Spol = "M",
                            Telefon = "061 201 022"
                        },
                        new
                        {
                            PacijentId = 5002,
                            Alergican = "Antibiotik",
                            BrojKartona = "19378A",
                            DatumRodjenja = "1980-05-08",
                            HronicneBolesti = "Nema",
                            Ime = "Helena",
                            Jmbg = "5089801236547",
                            Koagulopatije = false,
                            KorisnickoIme = "Pacijent2",
                            KorisnikId = 1002,
                            KrvnaGrupa = "A",
                            LozinkaHash = "O45OzDcnzIkz3i97ui6ExzI6kRk=",
                            LozinkaSalt = "9DtOOxfKEOqzx/vHnjsGLQ==",
                            MjestoRodjenja = "Mostar",
                            Prebivaliste = "Mostar",
                            Prezime = "Radic",
                            RhFaktor = "+",
                            Spol = "Z",
                            Telefon = "062 201 022"
                        },
                        new
                        {
                            PacijentId = 5003,
                            Alergican = "Ne",
                            BrojKartona = "8537C",
                            DatumRodjenja = "1992-11-12",
                            HronicneBolesti = "Nema",
                            Ime = "Melita",
                            Jmbg = "5089801236547",
                            Koagulopatije = false,
                            KorisnickoIme = "pacijent3",
                            KorisnikId = 1002,
                            KrvnaGrupa = "AB",
                            LozinkaHash = "r80ihzE7HGsM2xmAhL0HAjy4IaM=",
                            LozinkaSalt = "9DtOOxfKEOqzx/vHnjsGLQ==",
                            MjestoRodjenja = "Stolac",
                            Prebivaliste = "Mostar",
                            Prezime = "Golubica",
                            RhFaktor = "-",
                            Spol = "Z",
                            Telefon = "063 991 022"
                        });
                });

            modelBuilder.Entity("eKarton.Databases.PacijentOboljenje", b =>
                {
                    b.Property<int>("OboljenjeId")
                        .HasColumnType("int");

                    b.Property<int>("PacijentId")
                        .HasColumnType("int");

                    b.Property<string>("NesposobanZaRad")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NesposobanZaRadDo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NesposobanZaRadOd")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("OboljenjeId", "PacijentId");

                    b.HasIndex("PacijentId");

                    b.ToTable("PacijentOboljenje");

                    b.HasData(
                        new
                        {
                            OboljenjeId = 8010,
                            PacijentId = 5002,
                            NesposobanZaRad = "Ne",
                            NesposobanZaRadDo = " ",
                            NesposobanZaRadOd = " "
                        });
                });

            modelBuilder.Entity("eKarton.Databases.PacijentOsiguranje", b =>
                {
                    b.Property<int>("OsiguranjeId")
                        .HasColumnType("int");

                    b.Property<int>("PacijentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumOsiguranja")
                        .HasColumnType("date");

                    b.Property<bool>("Vazece")
                        .HasColumnType("bit");

                    b.HasKey("OsiguranjeId", "PacijentId")
                        .HasName("FK_PacijentOsiguranje");

                    b.HasIndex("PacijentId");

                    b.ToTable("PacijentOsiguranje");

                    b.HasData(
                        new
                        {
                            OsiguranjeId = 4001,
                            PacijentId = 5001,
                            DatumOsiguranja = new DateTime(2022, 9, 2, 11, 13, 54, 178, DateTimeKind.Local).AddTicks(8343),
                            Vazece = true
                        },
                        new
                        {
                            OsiguranjeId = 4002,
                            PacijentId = 5002,
                            DatumOsiguranja = new DateTime(2022, 9, 2, 11, 13, 54, 179, DateTimeKind.Local).AddTicks(354),
                            Vazece = true
                        },
                        new
                        {
                            OsiguranjeId = 4003,
                            PacijentId = 5003,
                            DatumOsiguranja = new DateTime(2022, 9, 2, 11, 13, 54, 179, DateTimeKind.Local).AddTicks(445),
                            Vazece = true
                        });
                });

            modelBuilder.Entity("eKarton.Databases.PacijentVakcinacija", b =>
                {
                    b.Property<int>("VakcinacijaId")
                        .HasColumnType("int");

                    b.Property<int>("PacijentId")
                        .HasColumnType("int");

                    b.Property<string>("Datum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Doza")
                        .HasColumnType("int");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VakcinacijaId", "PacijentId")
                        .HasName("FK_PacijentVakcinacija");

                    b.HasIndex("PacijentId");

                    b.ToTable("PacijentVakcinacija");

                    b.HasData(
                        new
                        {
                            VakcinacijaId = 7111,
                            PacijentId = 5002,
                            Datum = "2021-12-22",
                            Doza = 2,
                            Lokacija = "Mostar"
                        });
                });

            modelBuilder.Entity("eKarton.Databases.Pregled", b =>
                {
                    b.Property<int>("PregledId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("date");

                    b.Property<string>("Dijagnoza")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DoktorId")
                        .HasColumnType("int");

                    b.Property<int>("PacijentId")
                        .HasColumnType("int");

                    b.Property<string>("RazlogPosjete")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TerapijaId")
                        .HasColumnType("int");

                    b.Property<int>("UputnicaId")
                        .HasColumnType("int");

                    b.HasKey("PregledId");

                    b.HasIndex("DoktorId");

                    b.HasIndex("PacijentId");

                    b.HasIndex("TerapijaId");

                    b.HasIndex("UputnicaId");

                    b.ToTable("Pregled");

                    b.HasData(
                        new
                        {
                            PregledId = 6110,
                            Datum = new DateTime(2022, 9, 2, 11, 13, 54, 180, DateTimeKind.Local).AddTicks(9977),
                            Dijagnoza = "Upala srednjeg uha",
                            DoktorId = 3001,
                            PacijentId = 5001,
                            RazlogPosjete = "Bol  uhu i glava",
                            TerapijaId = 6001,
                            UputnicaId = 6100
                        });
                });

            modelBuilder.Entity("eKarton.Databases.PreventivneMjere", b =>
                {
                    b.Property<int>("MjereId")
                        .HasColumnType("int");

                    b.Property<int>("PacijentId")
                        .HasColumnType("int");

                    b.Property<string>("Stanje")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MjereId")
                        .HasName("PK_Mjere");

                    b.HasIndex("PacijentId");

                    b.ToTable("PreventivneMjere");

                    b.HasData(
                        new
                        {
                            MjereId = 8111,
                            PacijentId = 5003,
                            Stanje = "Alergijska reakcija"
                        });
                });

            modelBuilder.Entity("eKarton.Databases.SistematskiPregled", b =>
                {
                    b.Property<int>("SistematskiPregledId")
                        .HasColumnType("int");

                    b.Property<string>("Abdomen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Bmi")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BMI");

                    b.Property<string>("Cula")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("date");

                    b.Property<string>("Ekstremiteti")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GrudniKos")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KicmeniStub")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KrvniPritisak")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ObimGrudi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ObimStruka")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PacijentId")
                        .HasColumnType("int");

                    b.Property<string>("Pluca")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PromjeneNaKozi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Puls")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tezina")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tonzile")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Visina")
                        .HasColumnType("decimal(10,0)");

                    b.Property<string>("Vrat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SistematskiPregledId");

                    b.HasIndex("PacijentId");

                    b.ToTable("SistematskiPregled");
                });

            modelBuilder.Entity("eKarton.Databases.Terapija", b =>
                {
                    b.Property<int>("TerapijaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Do")
                        .HasColumnType("date")
                        .HasColumnName("DO");

                    b.Property<string>("NazivLijekova")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Od")
                        .HasColumnType("date")
                        .HasColumnName("OD");

                    b.Property<string>("Podsjetnik")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Uputa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TerapijaId");

                    b.ToTable("Terapija");

                    b.HasData(
                        new
                        {
                            TerapijaId = 6001,
                            Do = new DateTime(2022, 9, 9, 11, 13, 54, 179, DateTimeKind.Local).AddTicks(8403),
                            NazivLijekova = "Panklav",
                            Od = new DateTime(2022, 9, 2, 11, 13, 54, 179, DateTimeKind.Local).AddTicks(7446),
                            Podsjetnik = "Svako 12 sati",
                            Uputa = "2 puta na dan"
                        });
                });

            modelBuilder.Entity("eKarton.Databases.Termin", b =>
                {
                    b.Property<int>("TerminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("date");

                    b.Property<int>("DoktorId")
                        .HasColumnType("int");

                    b.Property<int>("PacijentId")
                        .HasColumnType("int");

                    b.Property<string>("Razlog")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Vrijeme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TerminId");

                    b.HasIndex("DoktorId");

                    b.HasIndex("PacijentId");

                    b.ToTable("Termin");

                    b.HasData(
                        new
                        {
                            TerminId = 7110,
                            Datum = new DateTime(2022, 9, 2, 11, 13, 54, 185, DateTimeKind.Local).AddTicks(5829),
                            DoktorId = 3009,
                            PacijentId = 5001,
                            Razlog = "rutinska kontrola",
                            Vrijeme = "09:15:00"
                        });
                });

            modelBuilder.Entity("eKarton.Databases.Uloga", b =>
                {
                    b.Property<int>("UlogaId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OpisUloge")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UlogaId");

                    b.ToTable("Uloga");

                    b.HasData(
                        new
                        {
                            UlogaId = 1,
                            Naziv = "Admin",
                            OpisUloge = "Upravljanje sistemom"
                        },
                        new
                        {
                            UlogaId = 2,
                            Naziv = "Korisnik",
                            OpisUloge = "Pregled podataka"
                        });
                });

            modelBuilder.Entity("eKarton.Databases.Uputnica", b =>
                {
                    b.Property<int>("UputnicaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("date");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Razlog")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UputnicaId");

                    b.ToTable("Uputnica");

                    b.HasData(
                        new
                        {
                            UputnicaId = 6100,
                            Datum = new DateTime(2022, 9, 4, 11, 13, 54, 180, DateTimeKind.Local).AddTicks(4824),
                            Naziv = "Posjeta orl doktora",
                            Razlog = "Upala uha"
                        });
                });

            modelBuilder.Entity("eKarton.Databases.Vakcinacija", b =>
                {
                    b.Property<int>("VakcinacijaId")
                        .HasColumnType("int");

                    b.Property<string>("NazivVakcine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VakcinacijaId");

                    b.ToTable("Vakcinacija");

                    b.HasData(
                        new
                        {
                            VakcinacijaId = 7111,
                            NazivVakcine = "Pfizer"
                        });
                });

            modelBuilder.Entity("eKarton.Databases.Administrator", b =>
                {
                    b.HasOne("eKarton.Databases.Bolnica", "Bolnica")
                        .WithMany("Administrators")
                        .HasForeignKey("BolnicaId")
                        .HasConstraintName("FK_AdministratorBolnica")
                        .IsRequired();

                    b.Navigation("Bolnica");
                });

            modelBuilder.Entity("eKarton.Databases.DodjeljeniDoktor", b =>
                {
                    b.HasOne("eKarton.Databases.Doktor", "Doktor")
                        .WithMany("DodjeljeniDoktors")
                        .HasForeignKey("DoktorId")
                        .HasConstraintName("FK__Dodjeljen__Dokto__3F466844")
                        .IsRequired();

                    b.HasOne("eKarton.Databases.Pacijent", "Pacijent")
                        .WithMany("DodjeljeniDoktors")
                        .HasForeignKey("PacijentId")
                        .HasConstraintName("FK__Dodjeljen__Pacij__3E52440B")
                        .IsRequired();

                    b.Navigation("Doktor");

                    b.Navigation("Pacijent");
                });

            modelBuilder.Entity("eKarton.Databases.Doktor", b =>
                {
                    b.HasOne("eKarton.Databases.Odjel", "Odjel")
                        .WithMany("Doktors")
                        .HasForeignKey("OdjelId")
                        .HasConstraintName("FK_OdjelDoktor")
                        .IsRequired();

                    b.Navigation("Odjel");
                });

            modelBuilder.Entity("eKarton.Databases.KorisnikUloga", b =>
                {
                    b.HasOne("eKarton.Databases.Korisnik", "Korisnik")
                        .WithMany("KorisnikUlogas")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK_KorisnikUloga")
                        .IsRequired();

                    b.HasOne("eKarton.Databases.Uloga", "Uloga")
                        .WithMany("KorisnikUlogas")
                        .HasForeignKey("UlogaId")
                        .HasConstraintName("FK_UlogaKorisnik")
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("eKarton.Databases.Nalaz", b =>
                {
                    b.HasOne("eKarton.Databases.Pacijent", "Pacijent")
                        .WithMany("Nalazs")
                        .HasForeignKey("PacijentId")
                        .HasConstraintName("FK_NalazPacijent")
                        .IsRequired();

                    b.Navigation("Pacijent");
                });

            modelBuilder.Entity("eKarton.Databases.OcjenaDoktora", b =>
                {
                    b.HasOne("eKarton.Databases.Doktor", "Doktor")
                        .WithMany("OcjenaDoktoras")
                        .HasForeignKey("DoktorId")
                        .HasConstraintName("FK_OcjenaDoktora")
                        .IsRequired();

                    b.Navigation("Doktor");
                });

            modelBuilder.Entity("eKarton.Databases.Odjel", b =>
                {
                    b.HasOne("eKarton.Databases.Bolnica", "Bolnica")
                        .WithMany("Odjels")
                        .HasForeignKey("BolnicaId")
                        .HasConstraintName("FK_OdjelBolnica")
                        .IsRequired();

                    b.Navigation("Bolnica");
                });

            modelBuilder.Entity("eKarton.Databases.Pacijent", b =>
                {
                    b.HasOne("eKarton.Databases.Korisnik", "Korisnik")
                        .WithMany("Pacijents")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK_PacijentKorisnik")
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("eKarton.Databases.PacijentOboljenje", b =>
                {
                    b.HasOne("eKarton.Databases.Oboljenje", "Oboljenje")
                        .WithMany("PacijentOboljenjes")
                        .HasForeignKey("OboljenjeId")
                        .HasConstraintName("FK__PacijentO__Obolj__60A75C0F")
                        .IsRequired();

                    b.HasOne("eKarton.Databases.Pacijent", "Pacijent")
                        .WithMany("PacijentOboljenjes")
                        .HasForeignKey("PacijentId")
                        .HasConstraintName("FK__PacijentO__Pacij__619B8048")
                        .IsRequired();

                    b.Navigation("Oboljenje");

                    b.Navigation("Pacijent");
                });

            modelBuilder.Entity("eKarton.Databases.PacijentOsiguranje", b =>
                {
                    b.HasOne("eKarton.Databases.Osiguranje", "Osiguranje")
                        .WithMany("PacijentOsiguranjes")
                        .HasForeignKey("OsiguranjeId")
                        .HasConstraintName("FK__PacijentO__Osigu__4222D4EF")
                        .IsRequired();

                    b.HasOne("eKarton.Databases.Pacijent", "Pacijent")
                        .WithMany("PacijentOsiguranjes")
                        .HasForeignKey("PacijentId")
                        .HasConstraintName("FK__PacijentO__Pacij__4316F928")
                        .IsRequired();

                    b.Navigation("Osiguranje");

                    b.Navigation("Pacijent");
                });

            modelBuilder.Entity("eKarton.Databases.PacijentVakcinacija", b =>
                {
                    b.HasOne("eKarton.Databases.Pacijent", "Pacijent")
                        .WithMany("PacijentVakcinacijas")
                        .HasForeignKey("PacijentId")
                        .HasConstraintName("FK__PacijentV__Pacij__59063A47")
                        .IsRequired();

                    b.HasOne("eKarton.Databases.Vakcinacija", "Vakcinacija")
                        .WithMany("PacijentVakcinacijas")
                        .HasForeignKey("VakcinacijaId")
                        .HasConstraintName("FK__PacijentV__Vakci__5812160E")
                        .IsRequired();

                    b.Navigation("Pacijent");

                    b.Navigation("Vakcinacija");
                });

            modelBuilder.Entity("eKarton.Databases.Pregled", b =>
                {
                    b.HasOne("eKarton.Databases.Doktor", "Doktor")
                        .WithMany("Pregleds")
                        .HasForeignKey("DoktorId")
                        .HasConstraintName("FK_PregledDoktor")
                        .IsRequired();

                    b.HasOne("eKarton.Databases.Pacijent", "Pacijent")
                        .WithMany("Pregleds")
                        .HasForeignKey("PacijentId")
                        .HasConstraintName("FK_PregledPacijent")
                        .IsRequired();

                    b.HasOne("eKarton.Databases.Terapija", "Terapija")
                        .WithMany("Pregleds")
                        .HasForeignKey("TerapijaId")
                        .HasConstraintName("FK_PregledTerapija")
                        .IsRequired();

                    b.HasOne("eKarton.Databases.Uputnica", "Uputnica")
                        .WithMany("Pregleds")
                        .HasForeignKey("UputnicaId")
                        .HasConstraintName("FK_PregledUputnica")
                        .IsRequired();

                    b.Navigation("Doktor");

                    b.Navigation("Pacijent");

                    b.Navigation("Terapija");

                    b.Navigation("Uputnica");
                });

            modelBuilder.Entity("eKarton.Databases.PreventivneMjere", b =>
                {
                    b.HasOne("eKarton.Databases.Pacijent", "Pacijent")
                        .WithMany("PreventivneMjeres")
                        .HasForeignKey("PacijentId")
                        .HasConstraintName("FK_PreventivneMjerePacijent")
                        .IsRequired();

                    b.Navigation("Pacijent");
                });

            modelBuilder.Entity("eKarton.Databases.SistematskiPregled", b =>
                {
                    b.HasOne("eKarton.Databases.Pacijent", "Pacijent")
                        .WithMany("SistematskiPregleds")
                        .HasForeignKey("PacijentId")
                        .HasConstraintName("FK_SistematskiPRegledPacijent")
                        .IsRequired();

                    b.Navigation("Pacijent");
                });

            modelBuilder.Entity("eKarton.Databases.Termin", b =>
                {
                    b.HasOne("eKarton.Databases.Doktor", "Doktor")
                        .WithMany("Termins")
                        .HasForeignKey("DoktorId")
                        .HasConstraintName("FK_TerminDoktor")
                        .IsRequired();

                    b.HasOne("eKarton.Databases.Pacijent", "Pacijent")
                        .WithMany("Termins")
                        .HasForeignKey("PacijentId")
                        .HasConstraintName("FK_TerminPacijent")
                        .IsRequired();

                    b.Navigation("Doktor");

                    b.Navigation("Pacijent");
                });

            modelBuilder.Entity("eKarton.Databases.Bolnica", b =>
                {
                    b.Navigation("Administrators");

                    b.Navigation("Odjels");
                });

            modelBuilder.Entity("eKarton.Databases.Doktor", b =>
                {
                    b.Navigation("DodjeljeniDoktors");

                    b.Navigation("OcjenaDoktoras");

                    b.Navigation("Pregleds");

                    b.Navigation("Termins");
                });

            modelBuilder.Entity("eKarton.Databases.Korisnik", b =>
                {
                    b.Navigation("KorisnikUlogas");

                    b.Navigation("Pacijents");
                });

            modelBuilder.Entity("eKarton.Databases.Oboljenje", b =>
                {
                    b.Navigation("PacijentOboljenjes");
                });

            modelBuilder.Entity("eKarton.Databases.Odjel", b =>
                {
                    b.Navigation("Doktors");
                });

            modelBuilder.Entity("eKarton.Databases.Osiguranje", b =>
                {
                    b.Navigation("PacijentOsiguranjes");
                });

            modelBuilder.Entity("eKarton.Databases.Pacijent", b =>
                {
                    b.Navigation("DodjeljeniDoktors");

                    b.Navigation("Nalazs");

                    b.Navigation("PacijentOboljenjes");

                    b.Navigation("PacijentOsiguranjes");

                    b.Navigation("PacijentVakcinacijas");

                    b.Navigation("Pregleds");

                    b.Navigation("PreventivneMjeres");

                    b.Navigation("SistematskiPregleds");

                    b.Navigation("Termins");
                });

            modelBuilder.Entity("eKarton.Databases.Terapija", b =>
                {
                    b.Navigation("Pregleds");
                });

            modelBuilder.Entity("eKarton.Databases.Uloga", b =>
                {
                    b.Navigation("KorisnikUlogas");
                });

            modelBuilder.Entity("eKarton.Databases.Uputnica", b =>
                {
                    b.Navigation("Pregleds");
                });

            modelBuilder.Entity("eKarton.Databases.Vakcinacija", b =>
                {
                    b.Navigation("PacijentVakcinacijas");
                });
#pragma warning restore 612, 618
        }
    }
}
